### Login Yusup
GET http://localhost:8080/auth/signin
Content-Type: application/json

{
  "device_token": "intexxlw",
  "ip_address": "1231123",
  "email": "yusuf@gmail.com",
  "password": "password"
}

### Refresh Token Yusup
GET http://localhost:8080/auth/refresh
Content-Type: application/json

{
  "refresh_token": "a233458c-edba-4744-86af-6b32a4075c91"
}

### Refresh Token Chathil
GET http://localhost:8080/auth/refresh
Content-Type: application/json

{
  "refresh_token" : "7c06d7d1-77de-4e00-8081-7f0fe53eff3a"
}

### Login Chathil
GET http://localhost:8080/auth/signin
Content-Type: application/json

{
  "device_token": "fakesstodken",
  "ip_address": "1231123",
  "email": "chathil98@gmail.com",
  "password": "password"
}

### Signup Ihza
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "device_token": "this is a uswer devive toksen sss23345ss",
  "ip_address": "192.200.020.210",
  "name": "Ihza SS",
  "email": "ihza@gmail.com",
  "password": "password"
}

### Login Ihza
GET http://localhost:8080/auth/signin
Content-Type: application/json

{
  "device_token": "this iss a usswer devive toksen sss23345ss",
  "ip_address": "192.200.020.210",
  "email": "ihza@gmail.com",
  "password": "password"
}

### Login Lakeesha from the hood
GET http://localhost:8080/auth/signin
Content-Type: application/json

{
  "device_token": "this is a uswer devive toksen sss23345sss",
  "ip_address": "192.200.020.210",
  "email": "lakeesha@gmail.com",
  "password": "password"
}

### Create Queue
POST http://localhost:8080/queue
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2IiwiaWF0IjoxNTk1Nzc3NzUzLCJleHAiOjE1OTU4MTAxNTN9.VlTudOiQ1K7l5kg6xLDyA38JLdPbl_2loOfUwA20cZykYgr4_6qAlxKaGdIuFZw8TKhuyIsE4D41PjOlwUo13g
Content-Type: application/json

{
  "id": "id2gene3ratedfrsssomclient",
  "name": "Contoh nama antrian 3",
  "desc": "Contoh deskripsi 111",
  "max": 100,
  "increment_by": 2,
  "valid_for": 32400000,
  "contact": "085306440054",
  "is_closed_queue": false,
  "ip_address": "192.189.220.222"
}