### Login Yusup
GET https://qcounter.herokuapp.com/auth/signin
Content-Type: application/json

{
  "device_token": "intexxlw",
  "ip_address": "1231123",
  "email": "yusuf@gmail.com",
  "password": "password"
}

### Refresh Token Yusup
GET https://qcounter.herokuapp.com/auth/refresh
Content-Type: application/json

{
  "refresh_token": "a233458c-edba-4744-86af-6b32a4075c91"
}

### Refresh Token Chathil
GET https://qcounter.herokuapp.com/auth/refresh
Content-Type: application/json

{
  "refresh_token" : "7c06d7d1-77de-4e00-8081-7f0fe53eff3a"
}

### Login Chathil
GET https://qcounter.herokuapp.com/auth/signin
Content-Type: application/json

{
  "device_token": "fakesstodken",
  "ip_address": "1231123",
  "email": "chathil98@gmail.com",
  "password": "password"
}

### Signup Ihza
POST https://qcounter.herokuapp.com/auth/signup
Content-Type: application/json

{
  "device_token": "this is a uswer devive toksen sss23345ss",
  "ip_address": "192.200.020.210",
  "name": "Ihza SS",
  "email": "ihza@gmail.com",
  "password": "password"
}

### Login Ihza
GET https://qcounter.herokuapp.com/auth/signin
Content-Type: application/json

{
  "device_token": "this iss a usswer devive toksen sss23345ss",
  "ip_address": "192.200.020.210",
  "email": "ihza@gmail.com",
  "password": "password"
}

### Refresh token Ihza
GET https://qcounter.herokuapp.com/auth/refresh
Content-Type: application/json

{
  "refresh_token" : "63e9be63-3508-4a97-bfdf-876493285c01"
}

### Login Lakeesha from the hood
GET https://qcounter.herokuapp.com/auth/signin
Content-Type: application/json

{
  "device_token": "this is a uswer devive toksen sss23345sss",
  "ip_address": "192.200.020.210",
  "email": "lakeesha@gmail.com",
  "password": "password"
}

### Create Queue
POST https://qcounter.herokuapp.com/queue
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTk2MTE2MzM5LCJleHAiOjE1OTYxNDg3Mzl9.9Y0CCMjH_NSWbaky08TEJ9CYLf0rfJxnP5ry91b2DDgOrn4gzTWrWk8nfi5Zm-JFQrk2AAEvEyIkG6QJ0COM-A
Content-Type: application/json

{
  "id": "id2gene3ratedfrsssosmclient",
  "name": "Contoh nama antrian 3",
  "desc": "Contoh deskripsi 111",
  "max": 100,
  "increment_by": 2,
  "valid_for": 32400000,
  "contact": "085306440054",
  "is_closed_queue": false,
  "ip_address": "192.189.220.222"
}

### Join a queue/ Get in line
POST https://qcounter.herokuapp.com:8080/queue/join
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNTk2MTE4ODc3LCJleHAiOjE1OTYxNTEyNzd9.ybRei0d8G7AznGODdlvd37dRo7aiNpRok16CRPkF_RF860y5asLL1rbgpWxXoB2Sd_IO-e_BzRg-awBSjTPNLg
Authorization: Bearer  eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTk2MTE2MzM5LCJleHAiOjE1OTYxNDg3Mzl9.9Y0CCMjH_NSWbaky08TEJ9CYLf0rfJxnP5ry91b2DDgOrn4gzTWrWk8nfi5Zm-JFQrk2AAEvEyIkG6QJ0COM-A
Content-Type: application/json

{
  "queue_id": "VlTudOiQ1K7l5kg6xLDyA38JLdPbl_2loOfUwA20cZykYgr4_6qAlxKaGdIuFZw8TKhuyIsE4D41PjOlwUo13g3",
  "ip_address": "192.1782.2222",
  "full_name": "Ihza Ahmad III",
  "contact": "0853005488"
}