package com.proximity.labs.qcounter.data.dto.request;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "Join Queue Request DTO", description = "The data required from user in order to join a queue.")
public class JoinQueueRequest {
    @ApiModelProperty(value = "queue id generated by client", required = true, allowableValues = "NonEmpty String", example = "KbFlP8A08y2k4Vp1XET", allowEmptyValue = false)
    @JsonProperty("queue_id")
    private String queueId;
    @ApiModelProperty(value = "IP address send from client at signup/ signup, this will be use to get the user creator location. Location is needed to make sure a user that want to join a queue can only join at a reasonable radius", required = true, allowableValues = "NonEmpty String", example = "180.251.7.251")
    @JsonProperty("ip_address")
    private String ipAddress;
    @ApiModelProperty(value = "user's full name or nickname", required = true, allowableValues = "NonEmpty String", example = "Abdul Chathil")
    @JsonProperty("full_name")
    private String fullName;
    @ApiModelProperty(value = "user's contact", required = true, allowableValues = "NonEmpty String", example = "+62 853 0644 0044")
    private String contact;

    public String getQueueId() {
        return queueId;
    }

    public void setQueueId(String queueId) {
        this.queueId = queueId;
    }

    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }


}