package com.proximity.labs.qcounter.data.dto.request;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "New Queue Request DTO", description = "The data required in order to create new queue.")
public class NewQueueRequest implements Request {

    @ApiModelProperty(name = "firebase like id generated on client side with the"
            + "help of firebase id generator. this id is generated by client to make the app more colaborative.", required = true, allowableValues = "NonEmpty String")
    @JsonProperty("id")        
    private String clientGeneratedId;

    @ApiModelProperty(name = "The queue name, this is not unique", example = "Antrian Bank BNI", required = true, allowableValues = "NonEmpty String, range[1, 20]")
    private String name;

    @ApiModelProperty(name = "Provides information about the queue", required = true, allowableValues = "String, range[0, 125]", allowEmptyValue = true)
    private String desc;

    @ApiModelProperty(name = "Maximum length of a queue in person", required = true, allowableValues = "Integer")
    private int max;

    @JsonProperty("increment_by")
    private int incrementBy;

    @ApiModelProperty(name = "Tells how long will this queue be", required = true, allowableValues = "Long")
    @JsonProperty("valid_for")
    private long validFor;

    @ApiModelProperty(name = "The creator contact, this can be any form of contact", required = true, allowableValues = "NonEmpty String, range[3, 25]")
    private String contact;

    @ApiModelProperty(name = "Tells if a queue can be searched or not, if true you can only join this queue via #QueueID or QRCODE")
    @JsonProperty("is_closed_queue")
    private boolean isClosedQueue;

    @ApiModelProperty(name = "IP addess is use to determined where is this queue created")
    @JsonProperty("ip_address")
    private String ipAddress;

    

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public int getMax() {
        return max;
    }

    public void setMax(int max) {
        this.max = max;
    }

    public int getIncrementBy() {
        return incrementBy;
    }

    public void setIncrementBy(int incrementBy) {
        this.incrementBy = incrementBy;
    }

    public long getValidFor() {
        return validFor;
    }

    public void setValidFor(long validFor) {
        this.validFor = validFor;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public boolean isClosedQueue() {
        return isClosedQueue;
    }

    public void setClosedQueue(boolean isClosedQueue) {
        this.isClosedQueue = isClosedQueue;
    }

    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public String getClientGeneratedId() {
        return clientGeneratedId;
    }

    public void setClientGeneratedId(String clientGeneratedId) {
        this.clientGeneratedId = clientGeneratedId;
    }

}