package com.proximity.labs.qcounter.data.dto.response;

import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.proximity.labs.qcounter.data.models.role.Role;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.beans.factory.annotation.Value;

@ApiModel(value = "Authentication Response", description = "API response when a user is authenticated")
public class AuthResponse {
    @ApiModelProperty(value = "user's table id")
    private final long id;
    @ApiModelProperty(value = "user's table id in hex")
    @JsonProperty("hex_id")
    private String hexId;
    @ApiModelProperty(value = "device token generated by firebase on client, this token is unique to each device and can be use to send notification via FCM.", required = true, allowableValues = "NonEmpty String")
    @JsonProperty("device_token")
    private final String deviceToken;
    @ApiModelProperty(value = "access token needed to access secured resources")
    @JsonProperty("access_token")
    private final String accessToken;
    @ApiModelProperty(value = "refresh token to refresh access token when expired")
    @JsonProperty("refresh_token")
    private String refreshToken;
    @ApiModelProperty(value = "Type of the token issued")
    @JsonProperty("token_type")
    private String tokenType = "Bearer ";
    @JsonProperty("expiry_duration")
    @ApiModelProperty(value = "The issued token's lifetime")
    private long expiryDuration;
    @ApiModelProperty(value = "IP address send from client at signup/ signup, this will be use to get the user creator location. Location is needed to make sure a user that want to join a queue can only join at a reasonable radius", required = true, allowableValues = "NonEmpty String", example = "180.251.7.251")
    @JsonProperty("ip_address")
    private final String ipAddress;
    @ApiModelProperty(value = "user's roles")
    private final Set<Role> roles;
    @ApiModelProperty(value = "user's name")
    private final String name;
    @ApiModelProperty(value = "user's email")
    private final String email;
    @ApiModelProperty(value = "user's profile picture")
    @JsonProperty("profile_picture")
    private final String profilePicture;
    @ApiModelProperty(value = "user's location determined from ip address")
    private final String location;
    @ApiModelProperty(value = "user's profile completion")
    @JsonProperty("profile_completion")
    private final int profileCompletion;
    @ApiModelProperty(value = "user's next queue")
    @JsonProperty("next_queue")
    private final String nextQueue = null;
    @ApiModelProperty(value = "user's owned queue")
    @JsonProperty("your_queue")
    private final String yourQueue = null;

    public AuthResponse(long id, String hexId, String deviceToken, String refreshToken, String accessToken, long expiryDuration, String ipAddress, Set<Role> roles, String name, String email,
                        String profilePicture, String location, int profileCompletion) {
        this.id = id;
        this.hexId = hexId;
        this.deviceToken = deviceToken;
        this.accessToken = accessToken;
        this.refreshToken = refreshToken;
        this.expiryDuration = expiryDuration;
        this.ipAddress = ipAddress;
        this.name = name;
        this.email = email;
        this.profilePicture = profilePicture;
        this.location = location;
        this.profileCompletion = profileCompletion;
        this.roles = roles;
    }

    public long getId() {
        return id;
    }

    public String getDeviceToken() {
        return deviceToken;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public String getIpAddress() {
        return ipAddress;
    }

    public String getName() {
        return name;
    }

    public String getEmail() {
        return email;
    }

    public String getProfilePicture() {
        return profilePicture;
    }

    public String getLocation() {
        return location;
    }

    public int getProfileCompletion() {
        return profileCompletion;
    }

    public String getNextQueue() {
        return nextQueue;
    }

    public String getYourQueue() {
        return yourQueue;
    }

    public String getRefreshToken() {
        return refreshToken;
    }

    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }

    public String getHexId() {
        return hexId;
    }

    public void setHexId(String hexId) {
        this.hexId = hexId;
    }

    public String getTokenType() {
        return tokenType;
    }

    public void setTokenType(String tokenType) {
        this.tokenType = tokenType;
    }

    public long getExpiryDuration() {
        return expiryDuration;
    }

    public void setExpiryDuration(long expiryDuration) {
        this.expiryDuration = expiryDuration;
    }

    public Set<Role> getRoles() {
        return roles;
    }
}